"""add preferred_node_id to model_group_members

Revision ID: 4fc665698bd8
Revises: 008_activity_log_enhancements
Create Date: 2026-05-03 01:28:00.258003

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4fc665698bd8'
down_revision = '008_activity_log_enhancements'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seed_history')
    op.add_column('model_group_members', sa.Column('preferred_node_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_model_group_members_preferred_node_id'), 'model_group_members', ['preferred_node_id'], unique=False)
    op.create_foreign_key(None, 'model_group_members', 'ollama_nodes', ['preferred_node_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_user_activity_logs_created_at', table_name='user_activity_logs')
    op.drop_index('ix_user_activity_logs_status_code', table_name='user_activity_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_activity_logs_status_code', 'user_activity_logs', ['status_code'], unique=False)
    op.create_index('ix_user_activity_logs_created_at', 'user_activity_logs', ['created_at'], unique=False)
    op.drop_constraint(None, 'model_group_members', type_='foreignkey')
    op.drop_index(op.f('ix_model_group_members_preferred_node_id'), table_name='model_group_members')
    op.drop_column('model_group_members', 'preferred_node_id')
    op.create_table('seed_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('seed_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('applied_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='seed_history_pkey'),
    sa.UniqueConstraint('seed_id', name='seed_history_seed_id_key')
    )
    # ### end Alembic commands ###

