"""add node_type to ollama_nodes

Revision ID: 577a1ea05175
Revises: 4fc665698bd8
Create Date: 2026-05-05 09:12:16.565957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '577a1ea05175'
down_revision = '4fc665698bd8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ollama_nodes', sa.Column('node_type', sa.String(length=50), server_default='ollama', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ollama_nodes', 'node_type')
    # ### end Alembic commands ###

