"""add_node_id_to_model_mappings

Revision ID: b0d015b37b53
Revises: 4d2246e200bb
Create Date: 2026-05-05 16:44:28.572337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0d015b37b53'
down_revision = '4d2246e200bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_mappings', sa.Column('node_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_model_mappings_node_id'), 'model_mappings', ['node_id'], unique=False)
    op.create_foreign_key(op.f('fk_model_mappings_node_id_ollama_nodes'), 'model_mappings', 'ollama_nodes', ['node_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_model_mappings_node_id_ollama_nodes'), 'model_mappings', type_='foreignkey')
    op.drop_index(op.f('ix_model_mappings_node_id'), table_name='model_mappings')
    op.drop_column('model_mappings', 'node_id')
    # ### end Alembic commands ###
