"""model group

Revision ID: b5af99d808ad
Revises: 007_model_groups
Create Date: 2026-04-24 17:47:33.851743

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b5af99d808ad'
down_revision = '007_model_groups'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seed_history')
    op.drop_constraint('model_groups_name_key', 'model_groups', type_='unique')
    op.alter_column('model_routing_rules', 'model_pattern',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Glob pattern: "glm-*", "qwen3-coder:*", "deepseek-*"',
               existing_nullable=False)
    op.alter_column('model_routing_rules', 'fallback_node_ids',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               comment=None,
               existing_comment='Array of fallback node IDs in order: [2, 3, 4]',
               existing_nullable=True)
    op.alter_column('model_routing_rules', 'load_balance_strategy',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               comment=None,
               existing_comment='round_robin, weighted, least_loaded, priority')
    op.drop_index('ix_routing_rules_active', table_name='model_routing_rules')
    op.drop_column('model_routing_rules', 'description')
    op.alter_column('node_load_metrics', 'active_requests',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='Currently active requests')
    op.alter_column('node_load_metrics', 'total_requests_today',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='Total requests served today')
    op.alter_column('node_load_metrics', 'avg_response_time_ms',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Rolling average response time',
               existing_nullable=True)
    op.alter_column('node_load_metrics', 'last_5_min_requests',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='Requests in last 5 minutes for rate limiting')
    op.alter_column('node_load_metrics', 'cpu_usage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=5, scale=2),
               comment=None,
               existing_comment='CPU usage percentage (if available from Ollama)',
               existing_nullable=True)
    op.alter_column('node_load_metrics', 'memory_usage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=5, scale=2),
               comment=None,
               existing_comment='Memory usage percentage (if available)',
               existing_nullable=True)
    op.drop_index('ix_node_load_metrics_node_time', table_name='node_load_metrics')
    op.create_index(op.f('ix_node_load_metrics_node_id'), 'node_load_metrics', ['node_id'], unique=False)
    op.drop_column('node_load_metrics', 'gpu_usage')
    op.alter_column('node_models', 'model_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Real model name from Ollama (e.g., glm-5:cloud)',
               existing_nullable=False)
    op.alter_column('node_models', 'model_size',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Model size in bytes',
               existing_nullable=True)
    op.alter_column('node_models', 'model_family',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Model family (glm, qwen, llama, etc.)',
               existing_nullable=True)
    op.alter_column('node_models', 'model_capabilities',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='{"completion": true, "vision": true, "tools": true}',
               existing_nullable=True)
    op.alter_column('node_models', 'model_digest',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Model SHA256 digest',
               existing_nullable=True)
    op.alter_column('node_models', 'last_seen',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When last detected by discovery',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('node_models', 'is_available',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Manual availability override',
               existing_nullable=False)
    op.drop_index('ix_node_models_available', table_name='node_models')
    op.drop_constraint('uq_node_model', 'node_models', type_='unique')
    op.create_index(op.f('ix_node_models_node_id'), 'node_models', ['node_id'], unique=False)
    op.create_unique_constraint('uq_node_model_name', 'node_models', ['node_id', 'model_name'])
    op.drop_column('node_models', 'request_count')
    op.drop_column('node_models', 'created_at')
    op.drop_column('node_models', 'updated_at')
    op.alter_column('ollama_nodes', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Friendly name: "main-server", "backup-1"',
               existing_nullable=False)
    op.alter_column('ollama_nodes', 'base_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Ollama server URL: http://194.87.188.8:11434',
               existing_nullable=False)
    op.alter_column('ollama_nodes', 'api_key',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Optional API key for authentication',
               existing_nullable=True)
    op.alter_column('ollama_nodes', 'priority',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Higher = preferred for fallback (100=primary, 50=backup)',
               existing_nullable=True)
    op.alter_column('ollama_nodes', 'weight',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Load balancing weight (higher = more traffic)',
               existing_nullable=True)
    op.alter_column('ollama_nodes', 'health_check_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Custom health check endpoint',
               existing_nullable=True)
    op.alter_column('ollama_nodes', 'health_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               comment=None,
               existing_comment='healthy, unhealthy, unknown')
    op.drop_index('ix_ollama_nodes_status', table_name='ollama_nodes')
    op.drop_column('ollama_nodes', 'metadata')
    op.drop_column('ollama_nodes', 'last_model_sync')
    op.drop_index('ix_user_activity_logs_user_id', table_name='user_activity_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_activity_logs_user_id', 'user_activity_logs', ['user_id'], unique=False)
    op.add_column('ollama_nodes', sa.Column('last_model_sync', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('ollama_nodes', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Additional node metadata'))
    op.create_index('ix_ollama_nodes_status', 'ollama_nodes', ['is_active', 'health_status'], unique=False)
    op.alter_column('ollama_nodes', 'health_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               comment='healthy, unhealthy, unknown')
    op.alter_column('ollama_nodes', 'health_check_url',
               existing_type=sa.VARCHAR(length=500),
               comment='Custom health check endpoint',
               existing_nullable=True)
    op.alter_column('ollama_nodes', 'weight',
               existing_type=sa.INTEGER(),
               comment='Load balancing weight (higher = more traffic)',
               existing_nullable=True)
    op.alter_column('ollama_nodes', 'priority',
               existing_type=sa.INTEGER(),
               comment='Higher = preferred for fallback (100=primary, 50=backup)',
               existing_nullable=True)
    op.alter_column('ollama_nodes', 'api_key',
               existing_type=sa.VARCHAR(length=500),
               comment='Optional API key for authentication',
               existing_nullable=True)
    op.alter_column('ollama_nodes', 'base_url',
               existing_type=sa.VARCHAR(length=500),
               comment='Ollama server URL: http://194.87.188.8:11434',
               existing_nullable=False)
    op.alter_column('ollama_nodes', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Friendly name: "main-server", "backup-1"',
               existing_nullable=False)
    op.add_column('node_models', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('node_models', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('node_models', sa.Column('request_count', sa.INTEGER(), autoincrement=False, nullable=True, comment='Total requests served for this model'))
    op.drop_constraint('uq_node_model_name', 'node_models', type_='unique')
    op.drop_index(op.f('ix_node_models_node_id'), table_name='node_models')
    op.create_unique_constraint('uq_node_model', 'node_models', ['node_id', 'model_name'])
    op.create_index('ix_node_models_available', 'node_models', ['model_name', 'is_available', 'node_id'], unique=False)
    op.alter_column('node_models', 'is_available',
               existing_type=sa.BOOLEAN(),
               comment='Manual availability override',
               existing_nullable=False)
    op.alter_column('node_models', 'last_seen',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When last detected by discovery',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('node_models', 'model_digest',
               existing_type=sa.VARCHAR(length=255),
               comment='Model SHA256 digest',
               existing_nullable=True)
    op.alter_column('node_models', 'model_capabilities',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='{"completion": true, "vision": true, "tools": true}',
               existing_nullable=True)
    op.alter_column('node_models', 'model_family',
               existing_type=sa.VARCHAR(length=100),
               comment='Model family (glm, qwen, llama, etc.)',
               existing_nullable=True)
    op.alter_column('node_models', 'model_size',
               existing_type=sa.BIGINT(),
               comment='Model size in bytes',
               existing_nullable=True)
    op.alter_column('node_models', 'model_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Real model name from Ollama (e.g., glm-5:cloud)',
               existing_nullable=False)
    op.add_column('node_load_metrics', sa.Column('gpu_usage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='GPU usage percentage (if available)'))
    op.drop_index(op.f('ix_node_load_metrics_node_id'), table_name='node_load_metrics')
    op.create_index('ix_node_load_metrics_node_time', 'node_load_metrics', ['node_id', 'recorded_at'], unique=False)
    op.alter_column('node_load_metrics', 'memory_usage',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               comment='Memory usage percentage (if available)',
               existing_nullable=True)
    op.alter_column('node_load_metrics', 'cpu_usage',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               comment='CPU usage percentage (if available from Ollama)',
               existing_nullable=True)
    op.alter_column('node_load_metrics', 'last_5_min_requests',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='Requests in last 5 minutes for rate limiting')
    op.alter_column('node_load_metrics', 'avg_response_time_ms',
               existing_type=sa.INTEGER(),
               comment='Rolling average response time',
               existing_nullable=True)
    op.alter_column('node_load_metrics', 'total_requests_today',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='Total requests served today')
    op.alter_column('node_load_metrics', 'active_requests',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='Currently active requests')
    op.add_column('model_routing_rules', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index('ix_routing_rules_active', 'model_routing_rules', ['model_pattern', 'is_active'], unique=False)
    op.alter_column('model_routing_rules', 'load_balance_strategy',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               comment='round_robin, weighted, least_loaded, priority')
    op.alter_column('model_routing_rules', 'fallback_node_ids',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               comment='Array of fallback node IDs in order: [2, 3, 4]',
               existing_nullable=True)
    op.alter_column('model_routing_rules', 'model_pattern',
               existing_type=sa.VARCHAR(length=255),
               comment='Glob pattern: "glm-*", "qwen3-coder:*", "deepseek-*"',
               existing_nullable=False)
    op.create_unique_constraint('model_groups_name_key', 'model_groups', ['name'])
    op.create_table('seed_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('seed_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('applied_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='seed_history_pkey'),
    sa.UniqueConstraint('seed_id', name='seed_history_seed_id_key')
    )
    # ### end Alembic commands ###

