"""add warmup_enabled to ollama_nodes

Revision ID: c8e2f4a9b1d2
Revises: b0d015b37b53
Create Date: 2026-05-05 11:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8e2f4a9b1d2'
down_revision = 'b0d015b37b53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ollama_nodes', sa.Column('warmup_enabled', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ollama_nodes', 'warmup_enabled')
    # ### end Alembic commands ###
