"""Grafana Assistant mock endpoints with in-memory chat store."""

import asyncio
import datetime
import json
import uuid
from typing import Any, Dict, Optional

from fastapi import APIRouter, Request, HTTPException, Query
from fastapi.responses import JSONResponse, StreamingResponse

import logging

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/grafana", tags=["Grafana Assistant"])

# ============================================================================
# Chat Memory Store (in-memory, per-process)
# ============================================================================

class _GrafanaChatStore:
    def __init__(self) -> None:
        self._chats: Dict[str, Any] = {}
        self._lock = asyncio.Lock()

    async def create_chat(self) -> Dict[str, Any]:
        chat_id = str(uuid.uuid4())
        now = datetime.datetime.utcnow().isoformat(timespec="milliseconds") + "Z"
        chat: Dict[str, Any] = {
            "id": chat_id,
            "created": now,
            "modified": now,
            "userId": "admin@localhost",
            "name": "New Chat",
            "nameAutogenerated": True,
            "category": "Other",
            "archived": False,
            "isPublic": False,
            "isImported": False,
            "inputTokens": 0,
            "outputTokens": 0,
            "cacheCreationInputTokens": 0,
            "cacheReadInputTokens": 0,
            "source": "assistant",
            "lastMode": "dashboarding",
            "messages": [],
        }
        async with self._lock:
            self._chats[chat_id] = chat
        return chat

    async def get_chat(self, chat_id: str) -> Any | None:
        async with self._lock:
            return self._chats.get(chat_id)

    async def add_message(self, chat_id: str, msg: Dict[str, Any]) -> Dict[str, Any]:
        msg.setdefault("id", str(uuid.uuid4()))
        msg.setdefault("created", datetime.datetime.utcnow().isoformat(timespec="milliseconds") + "Z")
        msg.setdefault("modified", msg["created"])
        msg.setdefault("type", "message")
        msg.setdefault("hidden", False)
        async with self._lock:
            chat = self._chats[chat_id]
            chat["messages"].append(msg)
            chat["modified"] = msg["created"]
        return msg

    async def list_chats(
        self,
        include_archived: bool = False,
        sources: Optional[list[str]] = None,
    ) -> list[Dict[str, Any]]:
        async with self._lock:
            chats = list(self._chats.values())
        if not include_archived:
            chats = [c for c in chats if not c.get("archived", False)]
        if sources is not None:
            chats = [c for c in chats if c.get("source") in sources]
        return chats


grafana_chat_store = _GrafanaChatStore()


# ============================================================================
# Logging helper
# ============================================================================

async def _log_grafana_request(request: Request) -> Dict[str, Any]:
    """Log every Grafana Assistant request for debugging."""
    method = request.method
    url = str(request.url)
    headers = dict(request.headers)
    client_host = request.client.host if request.client else "unknown"

    body_data = None
    if method in ("POST", "PUT", "PATCH"):
        try:
            body = await request.body()
            if body:
                try:
                    body_data = json.loads(body.decode("utf-8"))
                except json.JSONDecodeError:
                    body_data = body.decode("utf-8")
        except Exception as e:
            body_data = f"Error reading body: {e}"

    block = f"""
========== GRAFANA REQUEST ({method}) ==========
URL    : {url}
CLIENT : {client_host}
HEADERS:
{json.dumps(headers, indent=2, ensure_ascii=False)}
BODY   :
{json.dumps(body_data, indent=2, ensure_ascii=False) if body_data is not None else '(empty)'}
=============================================\n"""
    logger.info(block)
    return {
        "method": method,
        "url": url,
        "client": client_host,
        "headers": headers,
        "body": body_data,
    }


# ============================================================================
# Endpoints (Swagger'da ayrı ayrı görünür)
# ============================================================================

@router.get("/assistant/api/v1/settings/terms", include_in_schema=True)
async def grafana_terms(request: Request):
    """Grafana Assistant — Terms and Conditions"""
    await _log_grafana_request(request)
    return JSONResponse(
        status_code=200,
        content={
            "$schema": "https://assistant-prod-eu-central-0.grafana.net/schemas/ResponseBodyTermsAndConditionsResponse.json",
            "status": "success",
            "data": {
                "termsType": "msa",
                "version": "0.0.1-msa",
                "content": "\nFor legal information, please visit [Grafana Labs Terms and Conditions](https://grafana.com/legal/terms/)",
                "acceptedTermsAndConditions": True,
                "acceptedVersion": "0.0.1-msa",
            },
        },
    )


@router.put("/assistant/api/v1/settings/accept-terms", include_in_schema=True)
async def grafana_accept_terms(request: Request):
    """Grafana Assistant — Accept Terms and Conditions"""
    await _log_grafana_request(request)
    return JSONResponse(
        status_code=200,
        content={
            "$schema": "https://assistant-prod-eu-central-0.grafana.net/schemas/ResponseBodyTenantSettingResponse.json",
            "status": "success",
            "data": {
                "created": "2026-01-29T12:17:37.661Z",
                "modified": "2026-01-29T12:17:37.661Z",
                "acceptedTermsAndConditions": True,
                "version": "0.0.1-msa",
                "termsType": "msa",
                "infraMemoryEnabled": True,
            },
        },
    )


@router.get("/assistant/api/v1/discovery/infra/status", include_in_schema=True)
async def grafana_infra_discovery_status(request: Request):
    """Grafana Assistant — Infrastructure discovery status"""
    await _log_grafana_request(request)
    return JSONResponse(
        status_code=200,
        content={
            "$schema": "https://assistant-prod-eu-central-0.grafana.net/schemas/ResponseBodyInfraDiscoveryStatusResponse.json",
            "status": "success",
            "data": {
                "status": {
                    "available": False,
                },
            },
        },
    )


@router.get("/assistant/api/v1/settings", include_in_schema=True)
async def grafana_settings(request: Request):
    """Grafana Assistant — General Settings"""
    await _log_grafana_request(request)
    import urllib.parse

    url_parts = urllib.parse.urlsplit(str(request.url))
    base_url = f"{url_parts.scheme}://{url_parts.netloc}"
    return JSONResponse(
        status_code=200,
        content={
            "$schema": "https://assistant-prod-eu-central-0.grafana.net/schemas/ResponseBodySettingsResponse.json",
            "status": "success",
            "data": {
                "assistantEnabled": True,
                "assistantApiUrl": f"{base_url}/grafana",
                "assistantApiVersion": "v1",
                "features": {
                    "proactiveInsights": True,
                    "chat": True,
                    "investigate": True,
                    "mcp": True,
                },
                "limits": {
                    "maxPromptsPerDay": 1000,
                    "maxTokensPerPrompt": 8192,
                    "maxInvestigationsPerDay": 50,
                },
            },
        },
    )


@router.get("/assistant/api/v1/quickstarts", include_in_schema=True)
async def grafana_quickstarts(request: Request, enabled_only: bool = Query(False)):
    """Grafana Assistant — Quickstarts"""
    await _log_grafana_request(request)
    return JSONResponse(
        status_code=200,
        content={
            "$schema": "https://assistant-prod-eu-central-0.grafana.net/schemas/ResponseBodyQuickstartListResponse.json",
            "status": "success",
            "data": {
                "quickstarts": [],
                "pagination": {"total": 0, "limit": 20, "offset": 0},
            },
        },
    )


@router.post("/assistant/api/v1/ofrep/v1/evaluate/flags", include_in_schema=True)
async def grafana_flags(request: Request):
    """Grafana Assistant — OpenFeature flag evaluation"""
    await _log_grafana_request(request)
    return JSONResponse(
        status_code=200,
        content={
            "$schema": "https://ofrep/schemas/flagEvaluation.json",
            "flags": [
                {"key": "grafana.assistant.chat.enabled", "enabled": True, "reason": "STATIC", "value": True},
                {"key": "grafana.assistant.proactiveInsights.enabled", "enabled": True, "reason": "STATIC", "value": True},
                {"key": "grafana.assistant.mcp.enabled", "enabled": True, "reason": "STATIC", "value": True},
                {"key": "grafana.assistant.investigate.enabled", "enabled": True, "reason": "STATIC", "value": True},
            ],
        },
    )


@router.get("/assistant/api/v1/usage/limits/prompt", include_in_schema=True)
async def grafana_usage_limits_prompt(request: Request):
    """Grafana Assistant — Prompt usage limits"""
    await _log_grafana_request(request)
    return JSONResponse(
        status_code=200,
        content={
            "$schema": "https://assistant-prod-eu-central-0.grafana.net/schemas/ResponseBodyUserPromptCountResponse.json",
            "status": "success",
            "data": {"total": 2, "limit": 2000, "month": "2026-05"},
        },
    )


@router.get("/assistant/api/v1/usage/limits/investigation", include_in_schema=True)
async def grafana_usage_limits_investigation(request: Request):
    """Grafana Assistant — Investigation usage limits"""
    await _log_grafana_request(request)
    return JSONResponse(
        status_code=200,
        content={
            "$schema": "https://assistant-prod-eu-central-0.grafana.net/schemas/ResponseBodyInvestigationLimitResponse.json",
            "status": "success",
            "data": {"total": 0, "limit": 50, "month": "2026-05"},
        },
    )


@router.get("/assistant/api/v1/chats", include_in_schema=True)
async def grafana_chats(
    request: Request,
    limit: Optional[int] = Query(None, ge=1),
    offset: Optional[int] = Query(None, ge=0),
    includeArchived: Optional[bool] = Query(None),
    sources: Optional[list] = Query(None),
):
    """Grafana Assistant — List chats (or auto-create a new chat if empty)."""
    await _log_grafana_request(request)
    chats = await grafana_chat_store.list_chats(
        include_archived=includeArchived if includeArchived is not None else False,
        sources=sources,
    )

    # If store is empty and no explicit pagination, auto-create a chat and
    # return single-chat format (Grafana expects this when opening the panel).
    if not chats and limit is None and offset is None:
        chat = await grafana_chat_store.create_chat()
        return JSONResponse(
            status_code=200,
            content={
                "$schema": "https://assistant-prod-eu-central-0.grafana.net/schemas/ResponseBodyChatResponse.json",
                "status": "success",
                "data": chat,
            },
        )

    # Normal list mode
    count = len(chats)
    effective_limit = limit if limit is not None else 50
    effective_offset = offset if offset is not None else 0
    items = chats[effective_offset : effective_offset + effective_limit]
    return JSONResponse(
        status_code=200,
        content={
            "$schema": "https://assistant-prod-eu-central-0.grafana.net/schemas/ResponseBodyListResponseChat.json",
            "status": "success",
            "data": {
                "items": items,
                "pagination": {"total": count, "limit": effective_limit, "offset": effective_offset},
            },
        },
    )


@router.get("/assistant/api/v1/chats/{chat_id}", include_in_schema=True)
async def grafana_chat_detail(request: Request, chat_id: str):
    """Grafana Assistant — Get a single chat by ID"""
    await _log_grafana_request(request)
    chat = await grafana_chat_store.get_chat(chat_id)
    if not chat:
        raise HTTPException(status_code=404, detail="Chat not found")
    return JSONResponse(
        status_code=200,
        content={
            "$schema": "https://assistant-prod-eu-central-0.grafana.net/schemas/ResponseBodyChatResponse.json",
            "status": "success",
            "data": chat,
        },
    )


@router.post("/assistant/api/v1/chats/{chat_id}/messages", include_in_schema=True)
async def grafana_create_message(request: Request, chat_id: str):
    """Grafana Assistant — Create messages in a chat"""
    log = await _log_grafana_request(request)
    body = log.get("body")
    if isinstance(body, list):
        messages = body
    elif isinstance(body, dict):
        messages = [body]
    else:
        messages = []

    created: list[Dict[str, Any]] = []
    for msg in messages:
        chat = await grafana_chat_store.get_chat(chat_id)
        if not chat:
            await grafana_chat_store.create_chat()
            chat = await grafana_chat_store.get_chat(chat_id)
            if not chat:
                await grafana_chat_store.create_chat()
                grafana_chat_store._chats[chat_id] = grafana_chat_store._chats.pop(list(grafana_chat_store._chats.keys())[-1])
                grafana_chat_store._chats[chat_id]["id"] = chat_id
        await grafana_chat_store.add_message(chat_id, msg)
        created.append(msg)

    return JSONResponse(
        status_code=200,
        content={
            "$schema": "https://assistant-prod-eu-central-0.grafana.net/schemas/ResponseBodyListMessage.json",
            "status": "success",
            "data": created,
        },
    )


@router.get("/assistant/api/v1/chats/{chat_id}/prompt-stream", include_in_schema=True)
async def grafana_prompt_stream(
    request: Request,
    chat_id: str,
    application: Optional[str] = Query(None),
    audience: Optional[str] = Query(None),
):
    """Grafana Assistant — SSE prompt stream (returns assistant response)"""
    await _log_grafana_request(request)
    chat = await grafana_chat_store.get_chat(chat_id)
    if not chat:
        raise HTTPException(status_code=404, detail="Chat not found")

    message_id = str(uuid.uuid4())

    async def _sse():
        meta = json.dumps({"messageId": message_id, "chatId": chat_id, "role": "assistant"})
        yield f"data: {meta}\n\n"
        await asyncio.sleep(0.05)

        now = datetime.datetime.utcnow().isoformat(timespec="milliseconds") + "Z"
        nav_text = (
            "Merhaba! Size nasil yardimci olabilirim?\n\n"
            "<navigation_suggestions>\n"
            "[\n"
            '  {"type":"followup","input":{"intent":"What can you help me with?"},'
            '"label":"Neler yapabilirsin?",'
            '"tooltip":"Asistanin yetenekleri hakkinda bilgi al"},\n'
            '  {"type":"followup","input":{"intent":"Show me available dashboards"},'
            '"label":"Dashboardlari goster",'
            '"tooltip":"Mevcut Grafana dashboardlarini listele"},\n'
            '  {"type":"followup","input":{"intent":"Help me investigate an issue"},'
            '"label":"Sorun arastir",'
            '"tooltip":"Metrik, log veya trace ile sorun arastir"}\n'
            "]\n"
            "</navigation_suggestions>"
        )
        payload = json.dumps({
            "messages": [{
                "id": str(uuid.uuid4()),
                "created": now,
                "modified": now,
                "content": [{"text": nav_text, "type": "text"}],
                "role": "assistant",
                "senderName": "supervisor-single",
                "type": "message",
                "hidden": False,
            }],
            "stopReason": "end_turn",
            "usage": {
                "InputTokens": 3,
                "OutputTokens": 180,
                "CacheCreationInputTokens": 27817,
                "CacheReadInputTokens": 0,
            },
            "limits": {
                "weeklyUserPercentage": 0,
                "weeklyTenantPercentage": 0,
                "monthlyUserPromptCount": 3,
                "monthlyUserPromptLimit": 2000,
            },
            "model": "claude-sonnet-4-6",
        })
        yield f"data: {payload}\n\n"

    return StreamingResponse(
        _sse(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache, no-transform",
            "X-Accel-Buffering": "no",
        },
    )


@router.get("/assistant/api/v1/rules", include_in_schema=True)
async def grafana_rules(request: Request):
    """Grafana Assistant — List rules"""
    await _log_grafana_request(request)
    return JSONResponse(
        status_code=200,
        content={
            "$schema": "https://assistant-prod-eu-central-0.grafana.net/schemas/ResponseBodyRuleListResponse.json",
            "status": "success",
            "data": {
                "rules": [],
                "pagination": {"total": 0, "limit": 20, "offset": 0},
            },
        },
    )


@router.get("/assistant/api/v1/mcp-tools", include_in_schema=True)
async def grafana_mcp_tools(request: Request):
    """Grafana Assistant — List MCP tools"""
    await _log_grafana_request(request)
    return JSONResponse(
        status_code=200,
        content={
            "$schema": "https://assistant-prod-eu-central-0.grafana.net/schemas/ResponseBodyMCPToolsResponse.json",
            "status": "success",
            "data": {"tools": []},
        },
    )


@router.get("/assistant/api/v1/skills", include_in_schema=True)
async def grafana_skills(
    request: Request,
    limit: int = Query(100, ge=1),
    offset: int = Query(0, ge=0),
    scope: Optional[str] = Query("all"),
):
    """Grafana Assistant — List skills"""
    await _log_grafana_request(request)
    return JSONResponse(
        status_code=200,
        content={
            "$schema": "https://assistant-prod-eu-central-0.grafana.net/schemas/ResponseBodySkillListResponse.json",
            "status": "success",
            "data": {
                "skills": [],
                "pagination": {"total": 0, "limit": limit, "offset": offset},
            },
        },
    )


# ============================================================================
# Catch-all for unknown Grafana paths
# ============================================================================

@router.api_route("/{path:path}", methods=["GET", "POST", "PUT", "DELETE", "PATCH", "HEAD", "OPTIONS"])
async def grafana_catch_all(request: Request, path: str = ""):
    """Catch-all for unhandled Grafana Assistant paths. Logs for discovery."""
    await _log_grafana_request(request)
    return JSONResponse(
        status_code=200,
        content={"status": "received", "method": request.method, "path": path, "logged": True},
    )
