"""Grafana Assistant mock endpoints with in-memory chat store."""

import asyncio
import datetime
import json
import uuid
from typing import Any, Dict, Optional

from fastapi import APIRouter, Request, HTTPException, Query
from fastapi.responses import JSONResponse, StreamingResponse

import logging

logger = logging.getLogger(__name__)

# Lazy import proxy to avoid circular deps
try:
    from app.proxy import ollama_proxy
except Exception:
    ollama_proxy = None  # type: ignore


async def _get_grafana_model() -> str:
    """Read configured LLM model for Grafana Assistant from SystemConfig, fallback to first available mapped model."""
    from app.database import async_session_maker
    from app.models_db import SystemConfig

    async with async_session_maker() as session:
        row = await session.get(SystemConfig, "grafana_llm_model")
        if row and row.value:
            return row.value.strip()
    # fallback
    try:
        from app.config import model_mapper
        available = model_mapper.get_available_model_names()
        if available:
            return available[0]
    except Exception:
        pass
    return "default-model"


def _grafana_message_to_openai(msg: Dict[str, Any]) -> Dict[str, Any]:
    """Convert Grafana message format to OpenAI message."""
    role = msg.get("role", "user")
    content_parts = msg.get("content", [])
    if isinstance(content_parts, list):
        text_parts = [
            str(p.get("text", "")) for p in content_parts
            if isinstance(p, dict) and p.get("type") == "text"
        ]
        text = "".join(text_parts)
    else:
        text = str(content_parts)

    # Strip leading/trailing whitespace, especially from system prompts
    text = text.strip()

    openai_msg: Dict[str, Any] = {"role": role, "content": text}

    # Preserve tool calls / tool call ids if present
    if "tool_calls" in msg:
        openai_msg["tool_calls"] = msg["tool_calls"]
    if msg.get("tool_call_id"):
        openai_msg["tool_call_id"] = msg["tool_call_id"]
    if msg.get("name"):
        openai_msg["name"] = msg["name"]
    return openai_msg


def _grafana_messages_to_openai(body: Dict[str, Any]) -> list[Dict[str, Any]]:
    """Build OpenAI /v1/chat/completions messages list from Grafana prompt-stream body."""
    messages: list[Dict[str, Any]] = []

    # Grafana sends a large systemPrompt string describing tools and behavior.
    # If present, prepend it as a system message.
    system_prompt = body.get("systemPrompt")
    if system_prompt and isinstance(system_prompt, str):
        system_prompt = system_prompt.strip()
        if system_prompt:
            messages.append({"role": "system", "content": system_prompt})

    for msg in body.get("messages", []):
        if isinstance(msg, dict):
            messages.append(_grafana_message_to_openai(msg))

    return messages

router = APIRouter(prefix="/grafana", tags=["Grafana Assistant"])

# ============================================================================
# Chat Memory Store (in-memory, per-process)
# ============================================================================

class _GrafanaChatStore:
    def __init__(self) -> None:
        self._chats: Dict[str, Any] = {}
        self._lock = asyncio.Lock()

    async def create_chat(self) -> Dict[str, Any]:
        chat_id = str(uuid.uuid4())
        now = datetime.datetime.utcnow().isoformat(timespec="milliseconds") + "Z"
        chat: Dict[str, Any] = {
            "id": chat_id,
            "created": now,
            "modified": now,
            "userId": "admin@localhost",
            "name": "New Chat",
            "nameAutogenerated": True,
            "category": "Other",
            "archived": False,
            "isPublic": False,
            "isImported": False,
            "inputTokens": 0,
            "outputTokens": 0,
            "cacheCreationInputTokens": 0,
            "cacheReadInputTokens": 0,
            "source": "assistant",
            "lastMode": "dashboarding",
            "messages": [],
        }
        async with self._lock:
            self._chats[chat_id] = chat
        return chat

    async def get_chat(self, chat_id: str) -> Any | None:
        async with self._lock:
            return self._chats.get(chat_id)

    async def add_message(self, chat_id: str, msg: Dict[str, Any]) -> Dict[str, Any]:
        msg.setdefault("id", str(uuid.uuid4()))
        msg.setdefault("created", datetime.datetime.utcnow().isoformat(timespec="milliseconds") + "Z")
        msg.setdefault("modified", msg["created"])
        msg.setdefault("type", "message")
        msg.setdefault("hidden", False)
        async with self._lock:
            chat = self._chats[chat_id]
            chat["messages"].append(msg)
            chat["modified"] = msg["created"]
        return msg

    async def list_chats(
        self,
        include_archived: bool = False,
        sources: Optional[list[str]] = None,
    ) -> list[Dict[str, Any]]:
        async with self._lock:
            chats = list(self._chats.values())
        if not include_archived:
            chats = [c for c in chats if not c.get("archived", False)]
        if sources is not None:
            chats = [c for c in chats if c.get("source") in sources]
        return chats


grafana_chat_store = _GrafanaChatStore()


# ============================================================================
# Logging helper
# ============================================================================

async def _log_grafana_request(request: Request) -> Dict[str, Any]:
    """Log every Grafana Assistant request for debugging."""
    method = request.method
    url = str(request.url)
    headers = dict(request.headers)
    client_host = request.client.host if request.client else "unknown"

    body_data = None
    if method in ("POST", "PUT", "PATCH"):
        try:
            body = await request.body()
            if body:
                try:
                    body_data = json.loads(body.decode("utf-8"))
                except json.JSONDecodeError:
                    body_data = body.decode("utf-8")
        except Exception as e:
            body_data = f"Error reading body: {e}"

    block = f"""
========== GRAFANA REQUEST ({method}) ==========
URL    : {url}
CLIENT : {client_host}
HEADERS:
{json.dumps(headers, indent=2, ensure_ascii=False)}
BODY   :
{json.dumps(body_data, indent=2, ensure_ascii=False) if body_data is not None else '(empty)'}
=============================================\n"""
    logger.info(block)
    return {
        "method": method,
        "url": url,
        "client": client_host,
        "headers": headers,
        "body": body_data,
    }


# ============================================================================
# Endpoints (Swagger'da ayrı ayrı görünür)
# ============================================================================

@router.get("/assistant/api/v1/settings/terms", include_in_schema=True)
async def grafana_terms(request: Request):
    """Grafana Assistant — Terms and Conditions"""
    await _log_grafana_request(request)
    return JSONResponse(
        status_code=200,
        content={
            "$schema": "https://assistant-prod-eu-central-0.grafana.net/schemas/ResponseBodyTermsAndConditionsResponse.json",
            "status": "success",
            "data": {
                "termsType": "msa",
                "version": "0.0.1-msa",
                "content": "\nFor legal information, please visit [Grafana Labs Terms and Conditions](https://grafana.com/legal/terms/)",
                "acceptedTermsAndConditions": True,
                "acceptedVersion": "0.0.1-msa",
            },
        },
    )


@router.put("/assistant/api/v1/settings/accept-terms", include_in_schema=True)
async def grafana_accept_terms(request: Request):
    """Grafana Assistant — Accept Terms and Conditions"""
    await _log_grafana_request(request)
    return JSONResponse(
        status_code=200,
        content={
            "$schema": "https://assistant-prod-eu-central-0.grafana.net/schemas/ResponseBodyTenantSettingResponse.json",
            "status": "success",
            "data": {
                "created": "2026-01-29T12:17:37.661Z",
                "modified": "2026-01-29T12:17:37.661Z",
                "acceptedTermsAndConditions": True,
                "version": "0.0.1-msa",
                "termsType": "msa",
                "infraMemoryEnabled": True,
            },
        },
    )


@router.get("/assistant/api/v1/discovery/infra/status", include_in_schema=True)
async def grafana_infra_discovery_status(request: Request):
    """Grafana Assistant — Infrastructure discovery status"""
    await _log_grafana_request(request)
    return JSONResponse(
        status_code=200,
        content={
            "$schema": "https://assistant-prod-eu-central-0.grafana.net/schemas/ResponseBodyInfraDiscoveryStatusResponse.json",
            "status": "success",
            "data": {
                "status": {
                    "available": False,
                },
            },
        },
    )


@router.get("/assistant/api/v1/settings", include_in_schema=True)
async def grafana_settings(request: Request):
    """Grafana Assistant — General Settings"""
    await _log_grafana_request(request)
    import urllib.parse

    url_parts = urllib.parse.urlsplit(str(request.url))
    base_url = f"{url_parts.scheme}://{url_parts.netloc}"
    return JSONResponse(
        status_code=200,
        content={
            "$schema": "https://assistant-prod-eu-central-0.grafana.net/schemas/ResponseBodySettingsResponse.json",
            "status": "success",
            "data": {
                "assistantEnabled": True,
                "assistantApiUrl": f"{base_url}/grafana",
                "assistantApiVersion": "v1",
                "features": {
                    "proactiveInsights": True,
                    "chat": True,
                    "investigate": True,
                    "mcp": True,
                },
                "limits": {
                    "maxPromptsPerDay": 1000,
                    "maxTokensPerPrompt": 8192,
                    "maxInvestigationsPerDay": 50,
                },
            },
        },
    )


@router.get("/assistant/api/v1/quickstarts", include_in_schema=True)
async def grafana_quickstarts(request: Request, enabled_only: bool = Query(False)):
    """Grafana Assistant — Quickstarts"""
    await _log_grafana_request(request)
    return JSONResponse(
        status_code=200,
        content={
            "$schema": "https://assistant-prod-eu-central-0.grafana.net/schemas/ResponseBodyQuickstartListResponse.json",
            "status": "success",
            "data": {
                "quickstarts": [],
                "pagination": {"total": 0, "limit": 20, "offset": 0},
            },
        },
    )


@router.post("/assistant/api/v1/ofrep/v1/evaluate/flags", include_in_schema=True)
async def grafana_flags(request: Request):
    """Grafana Assistant — OpenFeature flag evaluation"""
    await _log_grafana_request(request)
    return JSONResponse(
        status_code=200,
        content={
            "$schema": "https://ofrep/schemas/flagEvaluation.json",
            "flags": [
                {"key": "grafana.assistant.chat.enabled", "enabled": True, "reason": "STATIC", "value": True},
                {"key": "grafana.assistant.proactiveInsights.enabled", "enabled": True, "reason": "STATIC", "value": True},
                {"key": "grafana.assistant.mcp.enabled", "enabled": True, "reason": "STATIC", "value": True},
                {"key": "grafana.assistant.investigate.enabled", "enabled": True, "reason": "STATIC", "value": True},
            ],
        },
    )


@router.get("/assistant/api/v1/usage/limits/prompt", include_in_schema=True)
async def grafana_usage_limits_prompt(request: Request):
    """Grafana Assistant — Prompt usage limits"""
    await _log_grafana_request(request)
    return JSONResponse(
        status_code=200,
        content={
            "$schema": "https://assistant-prod-eu-central-0.grafana.net/schemas/ResponseBodyUserPromptCountResponse.json",
            "status": "success",
            "data": {"total": 2, "limit": 2000, "month": "2026-05"},
        },
    )


@router.get("/assistant/api/v1/usage/limits/investigation", include_in_schema=True)
async def grafana_usage_limits_investigation(request: Request):
    """Grafana Assistant — Investigation usage limits"""
    await _log_grafana_request(request)
    return JSONResponse(
        status_code=200,
        content={
            "$schema": "https://assistant-prod-eu-central-0.grafana.net/schemas/ResponseBodyInvestigationLimitResponse.json",
            "status": "success",
            "data": {"total": 0, "limit": 50, "month": "2026-05"},
        },
    )


async def _grafana_chats_create_impl(request: Request) -> JSONResponse:
    """Shared implementation for creating a Grafana chat."""
    log_record = await _log_grafana_request(request)
    body = log_record.get("body") or {}

    chat = await grafana_chat_store.create_chat()
    # Override with client-provided defaults
    if "name" in body:
        chat["name"] = body["name"]
    if "nameAutogenerated" in body:
        chat["nameAutogenerated"] = body["nameAutogenerated"]
    if "origin" in body:
        chat["source"] = body["origin"].replace("oss/", "")

    return JSONResponse(
        status_code=200,
        content={
            "$schema": "https://assistant-prod-eu-central-0.grafana.net/schemas/ResponseBodyChatResponse.json",
            "status": "success",
            "data": chat,
        },
    )


async def _grafana_chats_list_impl(
    includeArchived: Optional[bool] = None,
    sources: Optional[list] = None,
    limit: Optional[int] = None,
    offset: Optional[int] = None,
) -> JSONResponse:
    """Shared implementation for listing Grafana chats."""
    chats = await grafana_chat_store.list_chats(
        include_archived=includeArchived if includeArchived is not None else False,
        sources=sources,
    )

    # If store is empty and no explicit pagination, auto-create a chat and
    # return single-chat format (Grafana expects this when opening the panel).
    if not chats and limit is None and offset is None:
        chat = await grafana_chat_store.create_chat()
        return JSONResponse(
            status_code=200,
            content={
                "$schema": "https://assistant-prod-eu-central-0.grafana.net/schemas/ResponseBodyChatResponse.json",
                "status": "success",
                "data": chat,
            },
        )

    # Normal list mode
    count = len(chats)
    effective_limit = limit if limit is not None else 50
    effective_offset = offset if offset is not None else 0
    items = chats[effective_offset : effective_offset + effective_limit]
    return JSONResponse(
        status_code=200,
        content={
            "$schema": "https://assistant-prod-eu-central-0.grafana.net/schemas/ResponseBodyListResponseChat.json",
            "status": "success",
            "data": {
                "items": items,
                "pagination": {"total": count, "limit": effective_limit, "offset": effective_offset},
            },
        },
    )


@router.post("/assistant/api/v1/chats", include_in_schema=True)
async def grafana_chats_create(request: Request):
    """Grafana Assistant — Create a new chat."""
    await _log_grafana_request(request)
    return await _grafana_chats_create_impl(request)


@router.get("/assistant/api/v1/chats", include_in_schema=True)
async def grafana_chats_list(
    request: Request,
    limit: Optional[int] = Query(None, ge=1),
    offset: Optional[int] = Query(None, ge=0),
    includeArchived: Optional[bool] = Query(None),
    sources: Optional[list] = Query(None),
):
    """Grafana Assistant — List chats."""
    await _log_grafana_request(request)
    return await _grafana_chats_list_impl(includeArchived, sources, limit, offset)


@router.get("/assistant/api/v1/chats/{chat_id}", include_in_schema=True)
async def grafana_chat_detail(request: Request, chat_id: str):
    """Grafana Assistant — Get a single chat by ID"""
    await _log_grafana_request(request)
    chat = await grafana_chat_store.get_chat(chat_id)
    if not chat:
        raise HTTPException(status_code=404, detail="Chat not found")
    return JSONResponse(
        status_code=200,
        content={
            "$schema": "https://assistant-prod-eu-central-0.grafana.net/schemas/ResponseBodyChatResponse.json",
            "status": "success",
            "data": chat,
        },
    )


@router.post("/assistant/api/v1/chats/{chat_id}/messages", include_in_schema=True)
async def grafana_create_message(request: Request, chat_id: str):
    """Grafana Assistant — Create messages in a chat"""
    log = await _log_grafana_request(request)
    body = log.get("body")
    if isinstance(body, list):
        messages = body
    elif isinstance(body, dict):
        messages = [body]
    else:
        messages = []

    created: list[Dict[str, Any]] = []
    for msg in messages:
        chat = await grafana_chat_store.get_chat(chat_id)
        if not chat:
            await grafana_chat_store.create_chat()
            chat = await grafana_chat_store.get_chat(chat_id)
            if not chat:
                await grafana_chat_store.create_chat()
                grafana_chat_store._chats[chat_id] = grafana_chat_store._chats.pop(list(grafana_chat_store._chats.keys())[-1])
                grafana_chat_store._chats[chat_id]["id"] = chat_id
        await grafana_chat_store.add_message(chat_id, msg)
        created.append(msg)

    return JSONResponse(
        status_code=200,
        content={
            "$schema": "https://assistant-prod-eu-central-0.grafana.net/schemas/ResponseBodyListMessage.json",
            "status": "success",
            "data": created,
        },
    )


@router.post("/assistant/api/v1/chats/{chat_id}/prompt-stream", include_in_schema=True)
async def grafana_prompt_stream(
    request: Request,
    chat_id: str,
    application: Optional[str] = Query(None),
    audience: Optional[str] = Query(None),
):
    """Grafana Assistant — SSE prompt stream (proxies to real LLM if configured)."""
    log_record = await _log_grafana_request(request)
    chat = await grafana_chat_store.get_chat(chat_id)
    if not chat:
        raise HTTPException(status_code=404, detail="Chat not found")

    message_id = str(uuid.uuid4())
    body = log_record.get("body") or {}
    chat_messages = body.get("messages", []) if isinstance(body, dict) else []  # type: ignore

    # Determine model
    model_label = "default-model"
    try:
        model_label = await _get_grafana_model()
    except Exception:
        pass

    # Build OpenAI messages from Grafana body
    openai_messages = _grafana_messages_to_openai(body)  # type: ignore

    # If proxy is available and we have messages, stream from real LLM.
    # Otherwise fall back to the static greeting mock.
    if ollama_proxy and openai_messages:
        user_ident = request.headers.get("x-grafana-user") or "grafana-user"
        openai_payload = {
            "model": model_label,
            "messages": openai_messages,
            "stream": True,
        }
        tools = body.get("tools") if isinstance(body, dict) else None  # type: ignore
        if tools and isinstance(tools, list):
            openai_payload["tools"] = tools  # type: ignore

        async def _real_sse():
            meta = json.dumps({"messageId": message_id, "chatId": chat_id, "role": "assistant"})
            yield f"data: {meta}\n\n"

            total_content = ""
            buffer = b""
            stream_finished = False

            try:
                async for raw_chunk in ollama_proxy.stream_ollama(openai_payload, model_name=model_label, username=user_ident):
                    if stream_finished:
                        break
                    if isinstance(raw_chunk, bytes):
                        buffer += raw_chunk
                    elif isinstance(raw_chunk, str):
                        buffer += raw_chunk.encode("utf-8")
                    else:
                        continue

                    while True:
                        line_end = buffer.find(b"\n")
                        if line_end == -1:
                            break
                        line = buffer[:line_end]
                        buffer = buffer[line_end + 1:]
                        line = line.strip()
                        if not line:
                            continue
                        if line.startswith(b"data: "):
                            line = line[6:].strip()
                        if line == b"[DONE]" or not line:
                            continue

                        try:
                            chunk_json = json.loads(line.decode("utf-8"))
                        except (json.JSONDecodeError, UnicodeDecodeError):
                            continue

                        choices = chunk_json.get("choices", [])
                        if not choices:
                            continue
                        delta = choices[0].get("delta", {})
                        content = delta.get("content", "")
                        if isinstance(content, str):
                            total_content += content
                        finish_reason = choices[0].get("finish_reason")

                        now = datetime.datetime.utcnow().isoformat(timespec="milliseconds") + "Z"
                        grafana_msg = {
                            "id": str(uuid.uuid4()),
                            "created": now,
                            "modified": now,
                            "content": [{"text": total_content, "type": "text"}],
                            "role": "assistant",
                            "senderName": "supervisor-single",
                            "type": "message",
                            "hidden": False,
                        }
                        payload_data = {
                            "messages": [grafana_msg],
                            "stopReason": finish_reason,
                            "usage": {
                                "InputTokens": 0,
                                "OutputTokens": len(total_content.split()),
                                "CacheCreationInputTokens": 0,
                                "CacheReadInputTokens": 0,
                            },
                            "limits": {
                                "weeklyUserPercentage": 0,
                                "weeklyTenantPercentage": 0,
                                "monthlyUserPromptCount": 3,
                                "monthlyUserPromptLimit": 2000,
                            },
                            "model": model_label,
                        }
                        if finish_reason:
                            stream_finished = True
                        yield f"data: {json.dumps(payload_data)}\nn\n"
                        if stream_finished:
                            break

                # Flush remaining buffer
                if buffer.strip():
                    remaining = buffer.strip()
                    if remaining.startswith(b"data: "):
                        remaining = remaining[6:].strip()
                    try:
                        chunk_json = json.loads(remaining.decode("utf-8"))
                        choices = chunk_json.get("choices", [])
                        if choices:
                            delta = choices[0].get("delta", {})
                            content = delta.get("content", "")
                            if isinstance(content, str):
                                total_content += content
                            finish_reason = choices[0].get("finish_reason")
                            now = datetime.datetime.utcnow().isoformat(timespec="milliseconds") + "Z"
                            grafana_msg = {
                                "id": str(uuid.uuid4()),
                                "created": now,
                                "modified": now,
                                "content": [{"text": total_content, "type": "text"}],
                                "role": "assistant",
                                "senderName": "supervisor-single",
                                "type": "message",
                                "hidden": False,
                            }
                            payload_data = {
                                "messages": [grafana_msg],
                                "stopReason": finish_reason or "end_turn",
                                "usage": {
                                    "InputTokens": 0,
                                    "OutputTokens": len(total_content.split()),
                                    "CacheCreationInputTokens": 0,
                                    "CacheReadInputTokens": 0,
                                },
                                "limits": {
                                    "weeklyUserPercentage": 0,
                                    "weeklyTenantPercentage": 0,
                                    "monthlyUserPromptCount": 3,
                                    "monthlyUserPromptLimit": 2000,
                                },
                                "model": model_label,
                            }
                            yield f"data: {json.dumps(payload_data)}\nn\n"
                    except Exception:
                        pass

            except Exception as exc:
                logger.error(f"Grafana LLM proxy error: {exc!r}")
                # Emit graceful error
                now = datetime.datetime.utcnow().isoformat(timespec="milliseconds") + "Z"
                err_msg = {
                    "id": str(uuid.uuid4()),
                    "created": now,
                    "modified": now,
                    "content": [{"text": f"LLM proxy error: {exc}", "type": "text"}],
                    "role": "assistant",
                    "senderName": "supervisor-single",
                    "type": "message",
                    "hidden": False,
                }
                yield f"data: {json.dumps({'messages': [err_msg], 'stopReason': 'end_turn', 'model': model_label})}\nn\n"

        return StreamingResponse(
            _real_sse(),
            media_type="text/event-stream",
            headers={
                "Cache-Control": "no-cache, no-transform",
                "X-Accel-Buffering": "no",
            },
        )

    # -------------------------------------------------------------------------
    # FALLBACK: static greeting (proxy unavailable or no messages)
    # -------------------------------------------------------------------------
    async def _sse():
        meta = json.dumps({"messageId": message_id, "chatId": chat_id, "role": "assistant"})
        yield f"data: {meta}\n\n"
        await asyncio.sleep(0.05)

        now = datetime.datetime.utcnow().isoformat(timespec="milliseconds") + "Z"
        nav_text = (
            "Merhaba! Size nasil yardimci olabilirim?\n\n"
            "<navigation_suggestions>\n"
            "[\n"
            '  {"type":"followup","input":{"intent":"What can you help me with?"},'
            '"label":"Neler yapabilirsin?",'
            '"tooltip":"Asistanin yetenekleri hakkinda bilgi al"},\n'
            '  {"type":"followup","input":{"intent":"Show me available dashboards"},'
            '"label":"Dashboardlari goster",'
            '"tooltip":"Mevcut Grafana dashboardlarini listele"},\n'
            '  {"type":"followup","input":{"intent":"Help me investigate an issue"},'
            '"label":"Sorun arastir",'
            '"tooltip":"Metrik, log veya trace ile sorun arastir"}\n'
            "]\n"
            "</navigation_suggestions>"
        )
        payload = json.dumps({
            "messages": [{
                "id": str(uuid.uuid4()),
                "created": now,
                "modified": now,
                "content": [{"text": nav_text, "type": "text"}],
                "role": "assistant",
                "senderName": "supervisor-single",
                "type": "message",
                "hidden": False,
            }],
            "stopReason": "end_turn",
            "usage": {
                "InputTokens": 3,
                "OutputTokens": 180,
                "CacheCreationInputTokens": 27817,
                "CacheReadInputTokens": 0,
            },
            "limits": {
                "weeklyUserPercentage": 0,
                "weeklyTenantPercentage": 0,
                "monthlyUserPromptCount": 3,
                "monthlyUserPromptLimit": 2000,
            },
            "model": model_label,
        })
        yield f"data: {payload}\n\n"

    return StreamingResponse(
        _sse(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache, no-transform",
            "X-Accel-Buffering": "no",
        },
    )


@router.get("/assistant/api/v1/rules", include_in_schema=True)
async def grafana_rules(request: Request):
    """Grafana Assistant — List rules"""
    await _log_grafana_request(request)
    return JSONResponse(
        status_code=200,
        content={
            "$schema": "https://assistant-prod-eu-central-0.grafana.net/schemas/ResponseBodyRuleListResponse.json",
            "status": "success",
            "data": {
                "rules": [],
                "pagination": {"total": 0, "limit": 20, "offset": 0},
            },
        },
    )


@router.get("/assistant/api/v1/mcp-tools", include_in_schema=True)
async def grafana_mcp_tools(request: Request):
    """Grafana Assistant — List MCP tools"""
    await _log_grafana_request(request)
    return JSONResponse(
        status_code=200,
        content={
            "$schema": "https://assistant-prod-eu-central-0.grafana.net/schemas/ResponseBodyMCPToolsResponse.json",
            "status": "success",
            "data": {"tools": []},
        },
    )


@router.get("/assistant/api/v1/skills", include_in_schema=True)
async def grafana_skills(
    request: Request,
    limit: int = Query(100, ge=1),
    offset: int = Query(0, ge=0),
    scope: Optional[str] = Query("all"),
):
    """Grafana Assistant — List skills"""
    await _log_grafana_request(request)
    return JSONResponse(
        status_code=200,
        content={
            "$schema": "https://assistant-prod-eu-central-0.grafana.net/schemas/ResponseBodySkillListResponse.json",
            "status": "success",
            "data": {
                "skills": [],
                "pagination": {"total": 0, "limit": limit, "offset": offset},
            },
        },
    )


# ============================================================================
# Catch-all for unknown Grafana paths
# ============================================================================

@router.api_route("/{path:path}", methods=["GET", "POST", "PUT", "DELETE", "PATCH", "HEAD"])
async def grafana_catch_all(request: Request, path: str = ""):
    """Catch-all for unhandled Grafana Assistant paths. Logs for discovery."""
    await _log_grafana_request(request)
    return JSONResponse(
        status_code=200,
        content={"status": "received", "method": request.method, "path": path, "logged": True},
    )
